# This is a basic workflow to help you get started with Actions

name: basic workflow

on: [push]

jobs:
  sh_test_job:
    name: sh test job
    runs-on: ubuntu-latest
    env: 
      working-directory: .github/workflows
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: giving permission to file
      run: sudo chmod 777 Kavya312/pycodeCheck/.github/workflows/runshs.sh
    - name: run a inline cmd
      run: echo hello. world!
    - name: run a schell script file and create file
      run: sh runshs.sh
      shell: bash
