# This is a basic workflow to help you get started with Actions

name: basic workflow

on: [push]

jobs:
  sh_test_job:
    name: sh test job
    runs-on: ubuntu-latest
    env: 
      working-directory: .github/workflows
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: run a inline cmd
      run: |
        echo hello. world!
        ls -a
        git version
        echo print path!!!!
        pwd
        echo got the path!!!
        echo giving permission......!!
        sudo chmod 777 run.sh
        echo running sh file..........!!!
        sudo sh run.sh
      shell: bash
