# This is a basic workflow to help you get started with Actions

name: basic workflow

on: [push]

jobs:
  sh_test_job:
    name: sh test job
    runs-on: ubuntu-latest
    env: 
      working-directory: .github/workflows
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: run sh script
      run: sudo sh run.sh
      shell: bash
    - name: run a inline cmd
      run: |
        echo hello. world!
        ls -a
        git version
        echo print path!!!!
        pwd
        echo got the path!!!
        echo giving permission......!!
        echo cd to workflow....!!!
        cd .github/workflows
        echo list workflow...!!!
        ls -a
        sudo chmod 777 runshs.sh
        echo running sh file..........!!!
        sudo sh runshs.sh
      shell: bash
    
