# This is a basic workflow to help you get started with Actions

name: basic workflow

on: [push]

jobs:
  sh_test_job:
    name: sh test job
    runs-on: windows-latest
    steps:
    - name: run a schell script file and create file
    - uses: actions/checkout@v3
    - run: sh Kavya312/pycodeCheck/run.sh
      shell: pwsh
